version: '3.8'

services:
  dbapp:
    build:
      context: ./dbapp
    container_name: dbapp
    ports:
      - "5000:5000"
    networks:
      - iris-net
    volumes:
      - dbdata:/app #named volume
  webapp:
    build:
      context: ./webapp
    container_name: webapp
    ports:
      - "8080:8080"
    depends_on:
      - dbapp
    networks:
      - iris-net

networks:
  iris-net:
    driver: bridge

volumes:
  dbdata: