worker_processes  1;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # HTTP Block
    server {
	    listen      80;
        server_name  localhost soothslayer.com api.soothslayer.com;

        # static files
        location /static {
            alias "C:/Users/milap/OneDrive/Desktop/CLG/FINAL LAP/7th Time/MLOps/deployments/statics/";
            add_header Cache-Control "public";
        }

        location / {
            proxy_pass        http://127.0.0.1:8080;
            proxy_set_header  Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
                	proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                	proxy_set_header   X-Forwarded-Proto $scheme;

	    	root   html;
	    	index  index.html;
        }
    }

    #HTTPS Block
    server {
        listen      443 ssl;
        server_name localhost soothslayer.com api.soothslayer.com;

        # Path to self-signed certificates
        ssl_certificate        "C:/Program Files/nginx/certs/cert.pem";
        ssl_certificate_key    "C:/Program Files/nginx/certs/key.pem";
        ssl_protocols          TLSv1.2 TLSv1.3;
        ssl_ciphers            HIGH:!aNULL:!MD5;

        location / {
            proxy_pass         http://127.0.0.1:8080;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
    }

}
